# Generated by Django 4.2.16 on 2024-10-22 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=65, verbose_name='tulliq ismi')),
                ('phone_number', models.TextField(blank=True, max_length=20, null=True, verbose_name='tellfon raqam')),
                ('telegram_id', models.CharField(max_length=8)),
                ('district', models.CharField(max_length=20, verbose_name='tuman')),
                ('level', models.IntegerField(default=0, verbose_name='daraja')),
                ('date_created', models.DateField()),
                ('date_update', models.DateField(auto_now=True)),
            ],
        ),
    ]
