# Generated by Django 4.2.16 on 2024-10-22 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyber_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
