# Generated by Django 4.2.16 on 2024-10-22 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyber_api', '0002_alter_person_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='tellfon raqam'),
        ),
    ]
