# Generated by Django 4.2.16 on 2024-10-24 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyber_api', '0003_questiontext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='option_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
